//// Internal — per-variant SVG defaults baked into the generated shards.
//// GENERATED by gg_icon_gen — do not hand-edit.

/// Baked onto every `lucide` icon's `<svg>`.
pub const lucide_defaults = [
  #("fill", "none"),
  #("stroke", "currentColor"),
  #("stroke-width", "2"),
  #("stroke-linecap", "round"),
  #("stroke-linejoin", "round"),
]
